<?xml version="1.0"?>
<!DOCTYPE graph [
	<!ELEMENT graph (node)*>
	<!ELEMENT node (edge)*>
	<!ELEMENT edge EMPTY>

	<!ATTLIST node
		label CDATA #REQUIRED
	>
	<!ATTLIST edge
		to     CDATA #REQUIRED
		weight CDATA #REQUIRED
	>
]>


<graph>
	<node label="(51|18)">
		<edge to="(51|18)" weight="0.0" />
		<edge to="(25|62)" weight="369.81644203177666" />
		<edge to="(15|53)" weight="289.02801672099343" />
		<edge to="(55|30)" weight="243.69310578367075" />
		<edge to="(52|60)" weight="273.4908122864115" />
		<edge to="(8|17)" weight="48.83904547348703" />
		<edge to="(43|88)" weight="106.2048172551812" />
		<edge to="(60|73)" weight="225.1163259402479" />
		<edge to="(35|20)" weight="208.71910786695636" />
		<edge to="(37|87)" weight="94.03890025439244" />
		<edge to="(80|34)" weight="47.6747466841763" />
		<edge to="(89|12)" weight="524.4458286002153" />
		<edge to="(8|29)" weight="238.90627381915857" />
		<edge to="(58|18)" weight="8.956765308610443" />
		<edge to="(33|90)" weight="138.66447669800624" />
		<edge to="(23|80)" weight="514.4378839848723" />
		<edge to="(90|51)" weight="265.54039876264795" />
		<edge to="(19|77)" weight="175.9045028830423" />
		<edge to="(57|51)" weight="210.06726938410668" />
		<edge to="(36|65)" weight="395.4820890106427" />
		<edge to="(67|67)" weight="63.16515711738422" />
		<edge to="(45|45)" weight="419.2048782554683" />
		<edge to="(38|72)" weight="210.1218699320891" />
		<edge to="(31|97)" weight="351.6070330132273" />
		<edge to="(30|65)" weight="56.56587797304963" />
		<edge to="(77|81)" weight="265.2560132342205" />
		<edge to="(35|41)" weight="340.59103318502343" />
		<edge to="(88|63)" weight="101.6269742373818" />
		<edge to="(84|62)" weight="443.15614563746624" />
		<edge to="(34|78)" weight="435.4825499718407" />
		<edge to="(13|91)" weight="236.2448219514759" />
		<edge to="(12|62)" weight="539.8307174881256" />
		<edge to="(84|75)" weight="107.3946943127579" />
		<edge to="(16|71)" weight="408.02253530347264" />
		<edge to="(97|57)" weight="497.4386502748556" />
		<edge to="(41|6)" weight="338.98244987125804" />
		<edge to="(98|32)" weight="302.3915973173833" />
	</node>
	<node label="(91|61)">
		<edge to="(51|18)" weight="433.90400641257787" />
		<edge to="(91|61)" weight="0.0" />
		<edge to="(25|62)" weight="127.25823907521276" />
		<edge to="(55|30)" weight="116.60434316301023" />
		<edge to="(86|93)" weight="442.23505026918957" />
		<edge to="(13|57)" weight="318.07559061559743" />
		<edge to="(35|20)" weight="334.17099860408655" />
		<edge to="(17|69)" weight="131.37218858254522" />
		<edge to="(5|58)" weight="86.87262303753451" />
		<edge to="(92|50)" weight="307.25988232931655" />
		<edge to="(38|72)" weight="305.81039845964733" />
		<edge to="(43|47)" weight="216.8648385922922" />
		<edge to="(67|73)" weight="394.60299822056186" />
		<edge to="(35|41)" weight="191.737967232436" />
		<edge to="(7|16)" weight="127.17225909417384" />
		<edge to="(84|62)" weight="155.9517587218914" />
		<edge to="(34|78)" weight="102.51537338100397" />
		<edge to="(13|91)" weight="344.0184934336407" />
		<edge to="(78|1)" weight="327.0684547600468" />
		<edge to="(60|48)" weight="121.99999636193841" />
		<edge to="(84|75)" weight="508.605388956006" />
		<edge to="(97|57)" weight="259.8892733619041" />
		<edge to="(57|22)" weight="226.4219302161302" />
		<edge to="(98|32)" weight="159.85028311246646" />
		<edge to="(41|10)" weight="274.6274014625353" />
		<edge to="(19|54)" weight="328.9329012681125" />
		<edge to="(15|53)" weight="223.17411645761456" />
		<edge to="(8|17)" weight="279.81095555475844" />
		<edge to="(41|20)" weight="333.8744750724149" />
		<edge to="(43|88)" weight="509.98354899370395" />
		<edge to="(60|73)" weight="170.34622774360284" />
		<edge to="(2|81)" weight="123.21570867108369" />
		<edge to="(86|41)" weight="90.64902511537986" />
		<edge to="(39|91)" weight="215.06584911426893" />
		<edge to="(24|47)" weight="536.2626710165111" />
		<edge to="(90|51)" weight="199.1935614565556" />
		<edge to="(57|51)" weight="52.74326464635851" />
		<edge to="(78|41)" weight="336.5352402842136" />
		<edge to="(49|45)" weight="405.7965305655207" />
		<edge to="(15|75)" weight="222.68045603598148" />
		<edge to="(36|65)" weight="293.827080140497" />
		<edge to="(94|59)" weight="358.9187846947958" />
		<edge to="(8|37)" weight="149.0184640136117" />
		<edge to="(16|46)" weight="245.2794969087508" />
		<edge to="(77|77)" weight="430.9340463783922" />
		<edge to="(77|81)" weight="196.69350276585047" />
		<edge to="(16|58)" weight="385.17860829466997" />
		<edge to="(95|44)" weight="390.0378331356735" />
		<edge to="(3|82)" weight="165.2365059400014" />
		<edge to="(16|71)" weight="283.3296534300694" />
		<edge to="(30|25)" weight="168.40966176142103" />
		<edge to="(92|23)" weight="168.68457226543347" />
	</node>
	<node label="(25|62)">
		<edge to="(51|18)" weight="421.69851451625584" />
		<edge to="(25|62)" weight="0.0" />
		<edge to="(55|30)" weight="309.4513334650334" />
		<edge to="(1|41)" weight="523.4728312039504" />
		<edge to="(5|52)" weight="51.425589264357924" />
		<edge to="(37|87)" weight="233.9699265848247" />
		<edge to="(17|69)" weight="88.81827629351326" />
		<edge to="(58|78)" weight="162.75926891548602" />
		<edge to="(92|50)" weight="202.40636926829882" />
		<edge to="(33|90)" weight="88.39187684625333" />
		<edge to="(5|71)" weight="98.67153365416885" />
		<edge to="(30|65)" weight="475.70792413867986" />
		<edge to="(67|73)" weight="504.0698706255754" />
		<edge to="(35|41)" weight="509.4246622334227" />
		<edge to="(7|16)" weight="527.235134372278" />
		<edge to="(84|62)" weight="316.7026521879606" />
		<edge to="(84|63)" weight="131.62329064107647" />
		<edge to="(53|2)" weight="175.5196233409441" />
		<edge to="(86|4)" weight="489.7145589924996" />
		<edge to="(13|91)" weight="136.4214948824412" />
		<edge to="(78|1)" weight="349.8021673383631" />
		<edge to="(84|75)" weight="133.11986261865397" />
		<edge to="(97|57)" weight="146.610802878534" />
		<edge to="(2|62)" weight="211.02595710013009" />
		<edge to="(98|32)" weight="280.32794028688545" />
		<edge to="(15|53)" weight="473.9559885915157" />
		<edge to="(16|23)" weight="455.4059679291186" />
		<edge to="(8|17)" weight="432.9129201141306" />
		<edge to="(60|73)" weight="245.29953551025437" />
		<edge to="(2|81)" weight="112.26839089401308" />
		<edge to="(8|29)" weight="339.0847656032796" />
		<edge to="(24|47)" weight="442.68948713595995" />
		<edge to="(23|80)" weight="239.52318176882585" />
		<edge to="(19|77)" weight="203.15857894572676" />
		<edge to="(57|51)" weight="397.75690606458" />
		<edge to="(17|11)" weight="263.23121182877105" />
		<edge to="(78|41)" weight="119.4229875514537" />
		<edge to="(49|45)" weight="401.09898044108405" />
		<edge to="(8|37)" weight="408.3087469220933" />
		<edge to="(16|46)" weight="504.8223685014279" />
		<edge to="(77|77)" weight="218.229897318875" />
		<edge to="(77|78)" weight="74.89336171090821" />
		<edge to="(31|97)" weight="145.83886893817441" />
		<edge to="(95|44)" weight="333.7020697033912" />
		<edge to="(3|82)" weight="364.2125564981972" />
		<edge to="(29|47)" weight="212.60675595150082" />
		<edge to="(98|91)" weight="381.1697041739253" />
		<edge to="(30|25)" weight="105.48772159207009" />
		<edge to="(71|34)" weight="349.89526887118944" />
		<edge to="(92|23)" weight="219.7000879056119" />
		<edge to="(38|35)" weight="469.73952375303685" />
	</node>
	<node label="(1|41)">
		<edge to="(51|18)" weight="150.62098572829038" />
		<edge to="(25|62)" weight="71.44142257664569" />
		<edge to="(1|41)" weight="0.0" />
		<edge to="(68|14)" weight="172.5367912600837" />
		<edge to="(5|52)" weight="141.6455474553645" />
		<edge to="(35|20)" weight="85.35161076837053" />
		<edge to="(80|34)" weight="93.58002552070484" />
		<edge to="(89|12)" weight="293.55225416775465" />
		<edge to="(17|69)" weight="393.46432466724474" />
		<edge to="(58|78)" weight="553.1503482863582" />
		<edge to="(55|45)" weight="527.2561968251237" />
		<edge to="(38|72)" weight="230.02531633188957" />
		<edge to="(5|71)" weight="70.66866432392028" />
		<edge to="(43|47)" weight="259.9819814145437" />
		<edge to="(67|73)" weight="447.2082756727723" />
		<edge to="(35|41)" weight="382.3615703169525" />
		<edge to="(84|62)" weight="107.38414828622771" />
		<edge to="(34|78)" weight="479.1148709554414" />
		<edge to="(53|2)" weight="221.38732537051746" />
		<edge to="(78|1)" weight="242.79192144131497" />
		<edge to="(98|21)" weight="514.8460372415948" />
		<edge to="(97|57)" weight="375.5440450897499" />
		<edge to="(2|62)" weight="125.35041815693216" />
		<edge to="(97|62)" weight="311.0833983510595" />
		<edge to="(57|22)" weight="99.98870781931154" />
		<edge to="(41|6)" weight="264.7580176111945" />
		<edge to="(98|32)" weight="180.03137004368705" />
		<edge to="(15|53)" weight="138.53975587741817" />
		<edge to="(52|60)" weight="480.19069424442523" />
		<edge to="(8|17)" weight="510.2381054374699" />
		<edge to="(41|20)" weight="311.68492982454893" />
		<edge to="(43|88)" weight="352.8835447282628" />
		<edge to="(60|73)" weight="362.33107041053097" />
		<edge to="(2|81)" weight="293.13877555496117" />
		<edge to="(73|62)" weight="139.35305325160027" />
		<edge to="(24|47)" weight="224.75187990440267" />
		<edge to="(58|18)" weight="326.6009907898448" />
		<edge to="(23|80)" weight="417.272604987249" />
		<edge to="(19|77)" weight="444.70088809460486" />
		<edge to="(57|51)" weight="109.78064416060339" />
		<edge to="(17|11)" weight="279.5457184668379" />
		<edge to="(78|41)" weight="288.04037353540514" />
		<edge to="(36|65)" weight="185.06853647750592" />
		<edge to="(77|77)" weight="392.3291311800471" />
		<edge to="(45|45)" weight="331.39518718800633" />
		<edge to="(77|78)" weight="323.4903217069725" />
		<edge to="(77|81)" weight="393.23776839354525" />
		<edge to="(16|58)" weight="348.7716681359466" />
		<edge to="(95|44)" weight="109.39966428754416" />
		<edge to="(71|23)" weight="472.0248287020148" />
		<edge to="(67|29)" weight="114.75834239207944" />
		<edge to="(30|25)" weight="505.0500947951634" />
		<edge to="(92|23)" weight="379.4811918180115" />
		<edge to="(25|53)" weight="383.14785594966634" />
	</node>
	<node label="(68|14)">
		<edge to="(51|18)" weight="55.19780398750447" />
		<edge to="(55|30)" weight="204.09204495845728" />
		<edge to="(86|93)" weight="194.0618847082741" />
		<edge to="(72|15)" weight="362.25062193036365" />
		<edge to="(68|14)" weight="0.0" />
		<edge to="(35|20)" weight="186.10309447383372" />
		<edge to="(37|87)" weight="84.36146876058477" />
		<edge to="(80|34)" weight="91.70556064485194" />
		<edge to="(17|69)" weight="112.202040430599" />
		<edge to="(55|45)" weight="104.4713675771287" />
		<edge to="(67|67)" weight="87.18989421471336" />
		<edge to="(43|47)" weight="102.95582943621915" />
		<edge to="(35|41)" weight="494.28702341652985" />
		<edge to="(88|63)" weight="522.3711026994544" />
		<edge to="(84|63)" weight="196.9224768918881" />
		<edge to="(34|78)" weight="441.1348223745458" />
		<edge to="(53|2)" weight="171.34311456133267" />
		<edge to="(89|43)" weight="470.8177695864367" />
		<edge to="(98|21)" weight="66.9187298944977" />
		<edge to="(60|48)" weight="321.09581813214965" />
		<edge to="(26|80)" weight="231.09163102717093" />
		<edge to="(2|62)" weight="100.04948557037471" />
		<edge to="(97|62)" weight="135.22325652772102" />
		<edge to="(57|22)" weight="232.95300249654431" />
		<edge to="(41|6)" weight="148.58009860107168" />
		<edge to="(19|53)" weight="252.15046307280048" />
		<edge to="(15|53)" weight="463.1269522136959" />
		<edge to="(16|23)" weight="209.92546461185435" />
		<edge to="(52|60)" weight="414.10555598013536" />
		<edge to="(43|88)" weight="498.92769224182734" />
		<edge to="(60|75)" weight="381.9790023473852" />
		<edge to="(2|81)" weight="404.0769636769063" />
		<edge to="(39|91)" weight="144.62907873362224" />
		<edge to="(73|62)" weight="299.00733450888225" />
		<edge to="(28|53)" weight="344.6753878450811" />
		<edge to="(23|80)" weight="177.03181988431743" />
		<edge to="(90|51)" weight="87.72343219463802" />
		<edge to="(17|11)" weight="240.59061201851227" />
		<edge to="(78|41)" weight="420.81268554910366" />
		<edge to="(49|45)" weight="306.7637220729929" />
		<edge to="(15|75)" weight="284.4224091836654" />
		<edge to="(36|65)" weight="554.5935618013782" />
		<edge to="(77|77)" weight="428.46654370222944" />
		<edge to="(45|45)" weight="429.9950376093498" />
		<edge to="(40|75)" weight="263.66394651781764" />
		<edge to="(77|81)" weight="294.7913087471149" />
		<edge to="(71|23)" weight="127.03873970002057" />
		<edge to="(12|62)" weight="81.37640979926964" />
		<edge to="(67|29)" weight="424.8016296264245" />
		<edge to="(25|53)" weight="112.22426139717845" />
		<edge to="(38|35)" weight="119.06317344727864" />
	</node>
	<node label="(35|20)">
		<edge to="(19|53)" weight="146.39750749486006" />
		<edge to="(19|54)" weight="265.3029158837881" />
		<edge to="(15|53)" weight="119.71236312097908" />
		<edge to="(55|30)" weight="22.41317838268048" />
		<edge to="(86|93)" weight="256.4517592111002" />
		<edge to="(16|23)" weight="466.7963213514628" />
		<edge to="(8|17)" weight="198.8117003941769" />
		<edge to="(13|57)" weight="431.96271735660986" />
		<edge to="(60|75)" weight="258.82324439634925" />
		<edge to="(5|52)" weight="221.87482566562738" />
		<edge to="(35|20)" weight="0.0" />
		<edge to="(89|12)" weight="99.63825919729359" />
		<edge to="(17|69)" weight="272.68356751305475" />
		<edge to="(58|78)" weight="68.72699067844123" />
		<edge to="(39|91)" weight="435.74187796770036" />
		<edge to="(73|62)" weight="475.60346711152" />
		<edge to="(8|29)" weight="355.2834480570521" />
		<edge to="(23|80)" weight="356.49319697897505" />
		<edge to="(19|77)" weight="541.1615933984829" />
		<edge to="(17|11)" weight="55.69672273777185" />
		<edge to="(78|41)" weight="103.08451231482297" />
		<edge to="(49|45)" weight="297.31559320352494" />
		<edge to="(8|37)" weight="524.7037228492608" />
		<edge to="(16|46)" weight="170.35792495649858" />
		<edge to="(43|47)" weight="77.64113587994099" />
		<edge to="(67|73)" weight="465.82068031594486" />
		<edge to="(35|41)" weight="462.87722684438774" />
		<edge to="(88|63)" weight="508.0566146890722" />
		<edge to="(7|16)" weight="440.84035451459033" />
		<edge to="(84|63)" weight="551.6335483061504" />
		<edge to="(53|2)" weight="494.38110793168914" />
		<edge to="(71|23)" weight="163.90755177237884" />
		<edge to="(29|47)" weight="70.8431232556738" />
		<edge to="(78|1)" weight="115.80234826842562" />
		<edge to="(16|71)" weight="189.1188134635743" />
		<edge to="(67|29)" weight="289.41560174028496" />
		<edge to="(30|25)" weight="340.44515369528864" />
		<edge to="(92|23)" weight="373.1329908152851" />
		<edge to="(2|62)" weight="370.5020073942995" />
		<edge to="(38|35)" weight="474.22860576179494" />
		<edge to="(97|62)" weight="147.38958217906998" />
		<edge to="(41|6)" weight="171.09698093401468" />
	</node>
	<node label="(17|69)">
		<edge to="(91|61)" weight="505.9262800038721" />
		<edge to="(55|30)" weight="462.38846760971" />
		<edge to="(37|87)" weight="515.0283730304089" />
		<edge to="(89|12)" weight="442.99673495847617" />
		<edge to="(17|69)" weight="0.0" />
		<edge to="(58|78)" weight="458.1535644372988" />
		<edge to="(5|58)" weight="41.967691247414905" />
		<edge to="(55|45)" weight="167.9705055762007" />
		<edge to="(33|90)" weight="220.85447598932427" />
		<edge to="(67|67)" weight="372.25945263215675" />
		<edge to="(87|88)" weight="246.0738476461001" />
		<edge to="(5|71)" weight="348.41949233899487" />
		<edge to="(43|47)" weight="306.25825353970146" />
		<edge to="(35|41)" weight="257.78044386911284" />
		<edge to="(7|16)" weight="411.04525360812784" />
		<edge to="(84|62)" weight="128.73326472735766" />
		<edge to="(84|63)" weight="286.2920321273438" />
		<edge to="(34|78)" weight="495.40840024613595" />
		<edge to="(86|4)" weight="294.08596840681304" />
		<edge to="(89|43)" weight="334.5733907077265" />
		<edge to="(26|80)" weight="261.1063105652081" />
		<edge to="(84|75)" weight="267.28430956833205" />
		<edge to="(57|22)" weight="222.1994766404852" />
		<edge to="(41|6)" weight="411.42107577261345" />
		<edge to="(41|10)" weight="190.35304217680084" />
		<edge to="(16|23)" weight="211.18578083819352" />
		<edge to="(41|20)" weight="539.4980502316567" />
		<edge to="(43|88)" weight="478.68015807537176" />
		<edge to="(39|91)" weight="216.20379126090643" />
		<edge to="(24|47)" weight="134.76482202402468" />
		<edge to="(78|41)" weight="276.73055184641447" />
		<edge to="(49|45)" weight="165.02294998218622" />
		<edge to="(15|75)" weight="148.95060069677496" />
		<edge to="(94|59)" weight="497.2198387706103" />
		<edge to="(16|46)" weight="145.6999067852479" />
		<edge to="(77|77)" weight="244.66649673329547" />
		<edge to="(45|45)" weight="186.84915202727655" />
		<edge to="(77|78)" weight="383.65767214668733" />
		<edge to="(40|75)" weight="236.62611104824316" />
		<edge to="(16|58)" weight="249.18650267677083" />
		<edge to="(95|44)" weight="157.58994301564633" />
		<edge to="(71|23)" weight="478.64181752237374" />
		<edge to="(12|62)" weight="10.70727615019484" />
		<edge to="(16|71)" weight="213.3172136831916" />
		<edge to="(98|91)" weight="228.53673026970665" />
		<edge to="(67|29)" weight="523.6796190556195" />
		<edge to="(92|23)" weight="553.1470601066485" />
		<edge to="(25|53)" weight="276.44176429147956" />
		<edge to="(38|35)" weight="239.33191334899965" />
	</node>
	<node label="(58|78)">
		<edge to="(41|10)" weight="541.1693150831035" />
		<edge to="(25|62)" weight="420.49010338027966" />
		<edge to="(15|53)" weight="160.14981191932728" />
		<edge to="(86|93)" weight="182.21476599889223" />
		<edge to="(72|15)" weight="293.7254290630354" />
		<edge to="(16|23)" weight="470.0538070333714" />
		<edge to="(52|60)" weight="402.0479656846735" />
		<edge to="(8|17)" weight="361.0024213074269" />
		<edge to="(60|75)" weight="417.81616490052454" />
		<edge to="(2|81)" weight="93.88133722518225" />
		<edge to="(5|52)" weight="283.21634924130177" />
		<edge to="(35|20)" weight="171.1047002456481" />
		<edge to="(37|87)" weight="483.67812493752314" />
		<edge to="(86|41)" weight="143.46006031598654" />
		<edge to="(17|69)" weight="462.24115353437816" />
		<edge to="(58|78)" weight="0.0" />
		<edge to="(73|62)" weight="85.78251627156989" />
		<edge to="(92|50)" weight="257.4567986472931" />
		<edge to="(24|47)" weight="453.6065842400883" />
		<edge to="(33|90)" weight="223.94982654438746" />
		<edge to="(28|53)" weight="484.46031041966864" />
		<edge to="(19|77)" weight="438.7103828737317" />
		<edge to="(74|36)" weight="441.56141376786" />
		<edge to="(49|45)" weight="362.26755470778704" />
		<edge to="(36|65)" weight="193.71656321181615" />
		<edge to="(94|59)" weight="312.08431673021573" />
		<edge to="(8|37)" weight="540.0375579004306" />
		<edge to="(77|78)" weight="80.24522932994097" />
		<edge to="(38|72)" weight="33.80047279633139" />
		<edge to="(30|65)" weight="68.6722177751504" />
		<edge to="(77|81)" weight="143.69922896291536" />
		<edge to="(67|73)" weight="132.6886236399395" />
		<edge to="(35|41)" weight="127.03903043272558" />
		<edge to="(88|63)" weight="384.8601225540817" />
		<edge to="(84|62)" weight="283.4870273645196" />
		<edge to="(16|58)" weight="479.100386097233" />
		<edge to="(95|44)" weight="58.47119097439892" />
		<edge to="(86|4)" weight="213.73876493410808" />
		<edge to="(3|82)" weight="138.9565368128366" />
		<edge to="(71|23)" weight="286.5146494403964" />
		<edge to="(12|62)" weight="75.57754187139508" />
		<edge to="(78|1)" weight="416.50013480878863" />
		<edge to="(98|91)" weight="514.0329279278525" />
		<edge to="(71|34)" weight="426.5093392777766" />
		<edge to="(2|62)" weight="72.8135499183118" />
		<edge to="(97|62)" weight="328.1564186308058" />
		<edge to="(57|22)" weight="343.7620900968367" />
		<edge to="(41|6)" weight="117.47218685715208" />
	</node>
	<node label="(92|50)">
		<edge to="(41|10)" weight="403.6364573220196" />
		<edge to="(19|53)" weight="407.6713916869171" />
		<edge to="(25|62)" weight="242.7978268216574" />
		<edge to="(55|30)" weight="67.15648686394064" />
		<edge to="(86|93)" weight="171.49695050261352" />
		<edge to="(72|15)" weight="468.2027105873317" />
		<edge to="(16|23)" weight="435.2998439420859" />
		<edge to="(1|41)" weight="509.66973951808365" />
		<edge to="(52|60)" weight="239.9470311471387" />
		<edge to="(8|17)" weight="467.81377928061454" />
		<edge to="(60|75)" weight="202.73675755709465" />
		<edge to="(5|52)" weight="336.4727626093535" />
		<edge to="(37|87)" weight="481.99709003828525" />
		<edge to="(80|34)" weight="351.39212692600745" />
		<edge to="(86|41)" weight="168.0626742258663" />
		<edge to="(58|78)" weight="438.09261890239077" />
		<edge to="(92|50)" weight="0.0" />
		<edge to="(55|45)" weight="379.5809133449912" />
		<edge to="(24|47)" weight="519.8620354277905" />
		<edge to="(58|18)" weight="365.76632173036745" />
		<edge to="(33|90)" weight="286.81767285176096" />
		<edge to="(28|53)" weight="475.15883626396874" />
		<edge to="(90|51)" weight="198.11120783927475" />
		<edge to="(57|51)" weight="110.01449713210262" />
		<edge to="(15|75)" weight="547.973661072771" />
		<edge to="(36|65)" weight="77.52011783685951" />
		<edge to="(67|67)" weight="320.2056784293578" />
		<edge to="(38|72)" weight="240.27733454725706" />
		<edge to="(31|97)" weight="214.0404213195174" />
		<edge to="(30|65)" weight="255.9545674453184" />
		<edge to="(35|41)" weight="189.6574362788224" />
		<edge to="(7|16)" weight="230.2055003369715" />
		<edge to="(34|78)" weight="204.82661846500025" />
		<edge to="(13|91)" weight="257.36581802945165" />
		<edge to="(3|82)" weight="178.42670103200632" />
		<edge to="(71|23)" weight="330.8167554035499" />
		<edge to="(29|47)" weight="364.39539438236136" />
		<edge to="(12|62)" weight="133.85811860728967" />
		<edge to="(98|21)" weight="174.09057537681744" />
		<edge to="(84|75)" weight="337.208690513786" />
		<edge to="(98|91)" weight="51.70720870126548" />
		<edge to="(67|29)" weight="449.03541891652156" />
		<edge to="(71|34)" weight="264.5169188273989" />
		<edge to="(2|62)" weight="263.6350018792486" />
		<edge to="(25|53)" weight="218.29622747413924" />
		<edge to="(97|62)" weight="506.43794491472636" />
		<edge to="(98|32)" weight="301.2422731766026" />
	</node>
	<node label="(33|90)">
		<edge to="(91|61)" weight="373.529165531638" />
		<edge to="(25|62)" weight="378.8241744336761" />
		<edge to="(72|15)" weight="479.3703544194207" />
		<edge to="(1|41)" weight="392.0484751486775" />
		<edge to="(13|57)" weight="77.74278299004831" />
		<edge to="(5|52)" weight="153.6153787898471" />
		<edge to="(89|12)" weight="182.57956209942688" />
		<edge to="(17|69)" weight="61.90373318679302" />
		<edge to="(5|58)" weight="130.79883267219776" />
		<edge to="(33|90)" weight="0.0" />
		<edge to="(87|88)" weight="314.3958085724296" />
		<edge to="(38|72)" weight="320.9434807919098" />
		<edge to="(5|71)" weight="345.2533453776728" />
		<edge to="(43|47)" weight="541.1005493358646" />
		<edge to="(67|73)" weight="142.44417828669287" />
		<edge to="(35|41)" weight="393.6876764057094" />
		<edge to="(88|63)" weight="268.90036128544347" />
		<edge to="(84|62)" weight="414.4239045964246" />
		<edge to="(84|63)" weight="511.7286703953593" />
		<edge to="(86|4)" weight="201.7073378360619" />
		<edge to="(13|91)" weight="181.19505019017524" />
		<edge to="(60|48)" weight="141.17799427553066" />
		<edge to="(26|80)" weight="24.183204415855204" />
		<edge to="(84|75)" weight="500.8836032595409" />
		<edge to="(97|57)" weight="545.0669274531532" />
		<edge to="(57|22)" weight="524.5357891966879" />
		<edge to="(98|32)" weight="501.76202509793575" />
		<edge to="(19|54)" weight="231.47816924499773" />
		<edge to="(16|23)" weight="390.80347964942166" />
		<edge to="(8|17)" weight="524.3267232759418" />
		<edge to="(86|41)" weight="145.11051426685907" />
		<edge to="(73|62)" weight="407.75820264876376" />
		<edge to="(24|47)" weight="75.20335570254993" />
		<edge to="(58|18)" weight="385.73555058120724" />
		<edge to="(23|80)" weight="45.362192530185965" />
		<edge to="(90|51)" weight="399.8594313510274" />
		<edge to="(19|77)" weight="102.89105690477396" />
		<edge to="(74|36)" weight="200.45666430407167" />
		<edge to="(57|51)" weight="94.75676923482563" />
		<edge to="(36|65)" weight="268.49859327912054" />
		<edge to="(94|59)" weight="119.10101184593682" />
		<edge to="(8|37)" weight="91.2476294573082" />
		<edge to="(77|77)" weight="248.24169657840213" />
		<edge to="(45|45)" weight="158.42300971085768" />
		<edge to="(77|78)" weight="229.63923811934967" />
		<edge to="(40|75)" weight="126.82453564289116" />
		<edge to="(77|81)" weight="447.73074977065517" />
		<edge to="(95|44)" weight="360.0207578693295" />
		<edge to="(3|82)" weight="443.4152612565915" />
		<edge to="(12|62)" weight="482.3148150554659" />
		<edge to="(16|71)" weight="111.90096528177507" />
		<edge to="(67|29)" weight="89.45826572474041" />
		<edge to="(92|23)" weight="111.27176324369552" />
		<edge to="(25|53)" weight="263.5198651246279" />
	</node>
	<node label="(67|67)">
		<edge to="(19|53)" weight="301.04197855013626" />
		<edge to="(15|53)" weight="269.9455585883576" />
		<edge to="(55|30)" weight="349.4816164201304" />
		<edge to="(72|15)" weight="129.93202837081662" />
		<edge to="(16|23)" weight="443.1713714262201" />
		<edge to="(52|60)" weight="275.82346926215905" />
		<edge to="(8|17)" weight="191.91246067940415" />
		<edge to="(13|57)" weight="221.7968001134983" />
		<edge to="(5|52)" weight="551.89568820251" />
		<edge to="(80|34)" weight="155.7289558012455" />
		<edge to="(86|41)" weight="363.56807260821734" />
		<edge to="(17|69)" weight="315.5309348777637" />
		<edge to="(58|78)" weight="241.7103980652171" />
		<edge to="(8|29)" weight="515.8546704516987" />
		<edge to="(55|45)" weight="422.42571588403507" />
		<edge to="(23|80)" weight="411.0736241733697" />
		<edge to="(57|51)" weight="287.8268053078766" />
		<edge to="(78|41)" weight="63.232477485757464" />
		<edge to="(49|45)" weight="114.12808986160172" />
		<edge to="(8|37)" weight="455.83964288876655" />
		<edge to="(16|46)" weight="509.6701788666037" />
		<edge to="(67|67)" weight="0.0" />
		<edge to="(45|45)" weight="37.15142646276348" />
		<edge to="(77|78)" weight="206.93876421759506" />
		<edge to="(87|88)" weight="500.71509156225807" />
		<edge to="(5|71)" weight="84.82335006756776" />
		<edge to="(67|73)" weight="377.57725611934717" />
		<edge to="(88|63)" weight="54.961311750638004" />
		<edge to="(16|58)" weight="411.16551117914264" />
		<edge to="(95|44)" weight="72.72923118277066" />
		<edge to="(13|91)" weight="301.76603089508984" />
		<edge to="(71|23)" weight="331.69435921766086" />
		<edge to="(89|43)" weight="110.73368486026455" />
		<edge to="(98|21)" weight="295.45474238804854" />
		<edge to="(26|80)" weight="220.9306869185824" />
		<edge to="(84|75)" weight="351.08231573994533" />
		<edge to="(16|71)" weight="229.3019222040608" />
		<edge to="(71|34)" weight="225.16115481082082" />
		<edge to="(92|23)" weight="317.04694738643684" />
		<edge to="(2|62)" weight="172.17386154786726" />
		<edge to="(38|35)" weight="238.41839661128824" />
		<edge to="(97|62)" weight="112.49919674295865" />
		<edge to="(57|22)" weight="447.9122375055574" />
		<edge to="(41|6)" weight="410.2321869704715" />
		<edge to="(98|32)" weight="115.71142516626416" />
	</node>
	<node label="(43|47)">
		<edge to="(51|18)" weight="332.39687100072325" />
		<edge to="(91|61)" weight="432.19201124392083" />
		<edge to="(25|62)" weight="75.18872454761322" />
		<edge to="(86|93)" weight="128.8393433528455" />
		<edge to="(72|15)" weight="163.99985207419317" />
		<edge to="(1|41)" weight="473.02103273773423" />
		<edge to="(68|14)" weight="291.80705453153325" />
		<edge to="(35|20)" weight="457.72162552680214" />
		<edge to="(37|87)" weight="460.5987584143126" />
		<edge to="(58|78)" weight="473.57523609383725" />
		<edge to="(92|50)" weight="336.9217789470514" />
		<edge to="(33|90)" weight="321.36376322740426" />
		<edge to="(67|67)" weight="216.36728933819265" />
		<edge to="(87|88)" weight="300.04947259753646" />
		<edge to="(38|72)" weight="502.5328126805108" />
		<edge to="(43|47)" weight="0.0" />
		<edge to="(67|73)" weight="467.99162290064226" />
		<edge to="(88|63)" weight="409.3644916395991" />
		<edge to="(7|16)" weight="339.19982524336586" />
		<edge to="(84|62)" weight="516.4467603498244" />
		<edge to="(84|63)" weight="157.42950066063418" />
		<edge to="(34|78)" weight="48.23603680347104" />
		<edge to="(78|1)" weight="360.7868010448277" />
		<edge to="(98|21)" weight="305.65001799535116" />
		<edge to="(60|48)" weight="143.89483133665397" />
		<edge to="(84|75)" weight="446.34746789922923" />
		<edge to="(97|57)" weight="424.9530638303879" />
		<edge to="(57|22)" weight="395.653995505911" />
		<edge to="(41|10)" weight="120.45608591032027" />
		<edge to="(19|53)" weight="198.41289330412306" />
		<edge to="(52|60)" weight="287.18918418715776" />
		<edge to="(8|17)" weight="483.2150349087304" />
		<edge to="(41|20)" weight="416.9546627361187" />
		<edge to="(60|73)" weight="435.42592754486475" />
		<edge to="(60|75)" weight="316.13178315625385" />
		<edge to="(2|81)" weight="360.5456446669376" />
		<edge to="(86|41)" weight="277.5202964457282" />
		<edge to="(73|62)" weight="101.41270940244286" />
		<edge to="(8|29)" weight="521.1666462876819" />
		<edge to="(58|18)" weight="529.3221853558626" />
		<edge to="(28|53)" weight="106.69734110210538" />
		<edge to="(57|51)" weight="345.29777627560804" />
		<edge to="(17|11)" weight="290.95703394458326" />
		<edge to="(78|41)" weight="327.5106060524532" />
		<edge to="(49|45)" weight="50.035806718778154" />
		<edge to="(8|37)" weight="131.91616408222336" />