<?xml version="1.0"?>
<!DOCTYPE graph [
	<!ELEMENT graph (node)*>
	<!ELEMENT node (edge)*>
	<!ELEMENT edge EMPTY>

	<!ATTLIST node
		label CDATA #REQUIRED
	>
	<!ATTLIST edge
		to     CDATA #REQUIRED
		weight CDATA #REQUIRED
	>
]>


<graph>
	<node label="(51|18)">
		<edge to="(51|18)" weight="0.0" />
		<edge to="(77|77)" weight="261.576577667925" />
		<edge to="(87|88)" weight="90.33373585856245" />
		<edge to="(43|47)" weight="342.6563996457623" />
		<edge to="(67|73)" weight="445.436159603945" />
		<edge to="(55|30)" weight="331.35782331572767" />
		<edge to="(52|60)" weight="273.4908122864115" />
		<edge to="(8|17)" weight="78.76078377516019" />
		<edge to="(41|20)" weight="179.58286579506236" />
		<edge to="(5|52)" weight="249.79599095465963" />
		<edge to="(89|43)" weight="418.60696432334186" />
		<edge to="(12|62)" weight="539.8307174881256" />
		<edge to="(5|58)" weight="125.40757805340104" />
		<edge to="(58|18)" weight="115.78520610484298" />
		<edge to="(74|36)" weight="375.3526672094871" />
		<edge to="(57|22)" weight="48.742301663385426" />
		<edge to="(8|37)" weight="438.5568819777623" />
		<edge to="(38|35)" weight="252.44492970202992" />
	</node>
	<node label="(91|61)">
		<edge to="(91|61)" weight="0.0" />
		<edge to="(38|72)" weight="208.7085680349913" />
		<edge to="(19|54)" weight="325.69027544205363" />
		<edge to="(43|47)" weight="55.08772726811463" />
		<edge to="(67|73)" weight="70.20174331286124" />
		<edge to="(16|23)" weight="322.89580122190023" />
		<edge to="(8|17)" weight="99.76889027855357" />
		<edge to="(5|52)" weight="110.10258245209496" />
		<edge to="(3|82)" weight="360.5856919111783" />
		<edge to="(35|20)" weight="83.95836715866044" />
		<edge to="(37|87)" weight="545.9083567319594" />
		<edge to="(89|43)" weight="172.0573540935112" />
		<edge to="(73|62)" weight="212.5493481541342" />
		<edge to="(84|75)" weight="452.7835809840957" />
		<edge to="(58|18)" weight="56.16008624008105" />
		<edge to="(23|80)" weight="517.013011010508" />
		<edge to="(98|91)" weight="375.3146008721697" />
		<edge to="(74|36)" weight="244.6846725805307" />
		<edge to="(57|51)" weight="211.96634001494854" />
		<edge to="(57|22)" weight="375.10168380055086" />
	</node>
	<node label="(55|30)">
		<edge to="(91|61)" weight="422.6837130533526" />
		<edge to="(19|54)" weight="536.2195284190753" />
		<edge to="(55|30)" weight="0.0" />
		<edge to="(1|41)" weight="116.35964668619518" />
		<edge to="(52|60)" weight="286.74305066584793" />
		<edge to="(41|20)" weight="472.11552027573174" />
		<edge to="(43|88)" weight="196.3330590462569" />
		<edge to="(35|20)" weight="287.12706758124193" />
		<edge to="(37|87)" weight="116.71558885434547" />
		<edge to="(5|58)" weight="353.5207164397069" />
		<edge to="(73|62)" weight="68.71131271660565" />
		<edge to="(24|47)" weight="105.38883604661893" />
		<edge to="(74|36)" weight="332.6063782456318" />
		<edge to="(19|77)" weight="297.8848578871108" />
		<edge to="(57|51)" weight="376.4082565290608" />
		<edge to="(8|37)" weight="457.1921722349898" />
		<edge to="(45|45)" weight="190.308147911703" />
		<edge to="(5|71)" weight="231.52549123360103" />
		<edge to="(43|47)" weight="388.5788345372492" />
		<edge to="(67|73)" weight="176.9167208142614" />
		<edge to="(7|16)" weight="198.88069091002592" />
		<edge to="(95|44)" weight="414.9528241399347" />
		<edge to="(3|82)" weight="148.30462135793397" />
		<edge to="(60|48)" weight="61.71582564142117" />
		<edge to="(92|23)" weight="135.23521826108737" />
		<edge to="(2|62)" weight="327.5874996160199" />
		<edge to="(97|62)" weight="141.18603886377153" />
	</node>
	<node label="(1|41)">
		<edge to="(51|18)" weight="124.13280070539946" />
		<edge to="(91|61)" weight="502.0422253607151" />
		<edge to="(15|53)" weight="148.45650424669964" />
		<edge to="(16|23)" weight="226.63686514757887" />
		<edge to="(1|41)" weight="0.0" />
		<edge to="(52|60)" weight="201.17848305619447" />
		<edge to="(68|14)" weight="312.2088190899637" />
		<edge to="(41|20)" weight="231.04691240678483" />
		<edge to="(43|88)" weight="332.24556046838376" />
		<edge to="(60|75)" weight="223.12804617998728" />
		<edge to="(5|58)" weight="18.284562561443853" />
		<edge to="(58|18)" weight="529.281048624438" />
		<edge to="(19|77)" weight="229.39290943043093" />
		<edge to="(8|37)" weight="25.365432101318362" />
		<edge to="(77|77)" weight="444.9473046235468" />
		<edge to="(45|45)" weight="189.5831837592839" />
		<edge to="(5|71)" weight="281.946415949593" />
		<edge to="(95|44)" weight="156.66609268885216" />
		<edge to="(3|82)" weight="209.8429557084066" />
		<edge to="(89|43)" weight="119.90070238722384" />
		<edge to="(60|48)" weight="319.8619668805878" />
		<edge to="(98|91)" weight="419.24699705752005" />
		<edge to="(92|23)" weight="300.4290629090161" />
		<edge to="(2|62)" weight="273.70196685260476" />
		<edge to="(57|22)" weight="233.81763470291415" />
	</node>
	<node label="(68|14)">
		<edge to="(51|18)" weight="148.13566584451004" />
		<edge to="(15|53)" weight="138.50736825612952" />
		<edge to="(55|30)" weight="391.20631328762164" />
		<edge to="(16|23)" weight="240.79905630796515" />
		<edge to="(68|14)" weight="0.0" />
		<edge to="(5|52)" weight="565.155486673412" />
		<edge to="(60|75)" weight="270.1340165156542" />
		<edge to="(17|69)" weight="153.1947968511753" />
		<edge to="(5|58)" weight="202.92902508745402" />
		<edge to="(24|47)" weight="137.43552311366048" />
		<edge to="(74|36)" weight="209.806593026306" />
		<edge to="(19|77)" weight="142.22649605343645" />
		<edge to="(16|46)" weight="225.16701089783075" />
		<edge to="(45|45)" weight="59.08799780720399" />
		<edge to="(87|88)" weight="210.74048674698852" />
		<edge to="(38|72)" weight="124.57074815838929" />
		<edge to="(67|73)" weight="519.6617579011183" />
		<edge to="(7|16)" weight="547.1980336128652" />
		<edge to="(3|82)" weight="355.4939492259719" />
		<edge to="(89|43)" weight="293.50767976789695" />
		<edge to="(29|47)" weight="385.5685781013394" />
		<edge to="(60|48)" weight="107.5433150664947" />
		<edge to="(84|75)" weight="172.37130201366693" />
		<edge to="(98|91)" weight="279.7203450197571" />
		<edge to="(2|62)" weight="487.1509399988364" />
		<edge to="(25|53)" weight="126.20311328168111" />
		<edge to="(97|62)" weight="325.0740515062553" />
		<edge to="(38|35)" weight="332.66328764704554" />
	</node>
	<node label="(5|52)">
		<edge to="(51|18)" weight="496.9742742097938" />
		<edge to="(77|77)" weight="287.8243698813747" />
		<edge to="(45|45)" weight="412.29597910987246" />
		<edge to="(91|61)" weight="352.057556920141" />
		<edge to="(67|73)" weight="142.1997328509201" />
		<edge to="(16|23)" weight="232.42005103592456" />
		<edge to="(7|16)" weight="505.9324849984744" />
		<edge to="(8|17)" weight="495.63070068494255" />
		<edge to="(41|20)" weight="463.5473540519088" />
		<edge to="(43|88)" weight="437.15387554411745" />
		<edge to="(5|52)" weight="0.0" />
		<edge to="(3|82)" weight="408.14290676317717" />
		<edge to="(35|20)" weight="72.92833388828265" />
		<edge to="(37|87)" weight="253.66270014261812" />
		<edge to="(29|47)" weight="510.9801100950046" />
		<edge to="(12|62)" weight="122.53486274477872" />
		<edge to="(60|48)" weight="532.9840409472131" />
		<edge to="(26|80)" weight="140.03678522949076" />
		<edge to="(58|18)" weight="364.9315891824631" />
		<edge to="(23|80)" weight="460.94282471177354" />
		<edge to="(19|77)" weight="250.06550905633983" />
		<edge to="(97|62)" weight="166.9792829855437" />
		<edge to="(38|35)" weight="339.74177901384456" />
		<edge to="(16|46)" weight="376.4490215193444" />
	</node>
	<node label="(35|20)">
		<edge to="(91|61)" weight="211.5805089301972" />
		<edge to="(1|41)" weight="135.5471165103985" />
		<edge to="(52|60)" weight="147.78924973950498" />
		<edge to="(43|88)" weight="494.23540602216883" />
		<edge to="(5|52)" weight="83.41440953736435" />
		<edge to="(60|75)" weight="350.26703655895795" />
		<edge to="(35|20)" weight="0.0" />
		<edge to="(37|87)" weight="167.33091012612647" />
		<edge to="(17|69)" weight="97.5906609075471" />
		<edge to="(5|58)" weight="409.63016742169134" />
		<edge to="(73|62)" weight="351.8509826663568" />
		<edge to="(58|18)" weight="276.2130702687065" />
		<edge to="(19|77)" weight="463.6547049620714" />
		<edge to="(57|51)" weight="249.05352915290155" />
		<edge to="(8|37)" weight="174.53645839674763" />
		<edge to="(77|77)" weight="379.03648934076824" />
		<edge to="(45|45)" weight="314.1395671549298" />
		<edge to="(87|88)" weight="570.798218490361" />
		<edge to="(67|73)" weight="279.46680131200725" />
		<edge to="(7|16)" weight="402.1440636366652" />
		<edge to="(95|44)" weight="303.58419755656996" />
		<edge to="(3|82)" weight="377.1251803492593" />
		<edge to="(89|43)" weight="407.05569268026926" />
		<edge to="(29|47)" weight="43.010437503010955" />
		<edge to="(60|48)" weight="59.305377872458656" />
		<edge to="(84|75)" weight="503.19803737329084" />
		<edge to="(98|91)" weight="494.6686045043185" />
		<edge to="(2|62)" weight="209.80080681481203" />
		<edge to="(57|22)" weight="178.11283305754924" />
		<edge to="(38|35)" weight="487.22616301258336" />
	</node>
	<node label="(37|87)">
		<edge to="(77|77)" weight="94.12584980346843" />
		<edge to="(45|45)" weight="288.3008351197018" />
		<edge to="(87|88)" weight="250.90697808876658" />
		<edge to="(5|71)" weight="508.8853389823968" />
		<edge to="(19|54)" weight="250.40325448452927" />
		<edge to="(67|73)" weight="214.8611335017946" />
		<edge to="(15|53)" weight="81.35018351405465" />
		<edge to="(16|23)" weight="278.9645450237169" />
		<edge to="(52|60)" weight="113.50162944298764" />
		<edge to="(7|16)" weight="117.48105511324971" />
		<edge to="(41|20)" weight="187.21996374103173" />
		<edge to="(60|75)" weight="511.18034897961564" />
		<edge to="(35|20)" weight="196.97069164412045" />
		<edge to="(37|87)" weight="0.0" />
		<edge to="(5|58)" weight="57.45615104848979" />
		<edge to="(73|62)" weight="310.33671583386507" />
		<edge to="(58|18)" weight="136.47794493262813" />
		<edge to="(74|36)" weight="263.9900872644867" />
		<edge to="(19|77)" weight="285.72681362930155" />
		<edge to="(57|51)" weight="413.6778991967208" />
		<edge to="(25|53)" weight="362.1556127930772" />
		<edge to="(97|62)" weight="480.80564144270875" />
		<edge to="(57|22)" weight="346.2271971486556" />
	</node>
	<node label="(17|69)">
		<edge to="(91|61)" weight="122.10747933079934" />
		<edge to="(15|53)" weight="302.2918352356008" />
		<edge to="(55|30)" weight="341.16986614720497" />
		<edge to="(16|23)" weight="198.87207044604853" />
		<edge to="(1|41)" weight="388.56407121286304" />
		<edge to="(8|17)" weight="71.2137617257971" />
		<edge to="(68|14)" weight="112.7402211613282" />
		<edge to="(41|20)" weight="244.08648128821073" />
		<edge to="(60|75)" weight="408.81896002477646" />
		<edge to="(17|69)" weight="0.0" />
		<edge to="(5|58)" weight="168.8408954074366" />
		<edge to="(73|62)" weight="477.25459813920315" />
		<edge to="(58|18)" weight="385.8936412822286" />
		<edge to="(23|80)" weight="322.5590676066361" />
		<edge to="(19|77)" weight="297.0556882024627" />
		<edge to="(8|37)" weight="425.261865728517" />
		<edge to="(16|46)" weight="517.4073177738594" />
		<edge to="(45|45)" weight="401.7051112246117" />
		<edge to="(87|88)" weight="109.72812528335666" />
		<edge to="(67|73)" weight="84.3402059078569" />
		<edge to="(7|16)" weight="115.49049258789744" />
		<edge to="(95|44)" weight="473.3030049970132" />
		<edge to="(29|47)" weight="252.24946179477593" />
		<edge to="(60|48)" weight="499.5029566618957" />
		<edge to="(84|75)" weight="212.6445012518172" />
		<edge to="(92|23)" weight="205.53485961381193" />
		<edge to="(2|62)" weight="385.2170840038189" />
		<edge to="(97|62)" weight="232.43940790068953" />
		<edge to="(38|35)" weight="47.582536546302705" />
	</node>
	<node label="(5|58)">
		<edge to="(87|88)" weight="155.69727287724302" />
		<edge to="(43|47)" weight="110.41597583889045" />
		<edge to="(15|53)" weight="90.32329684398016" />
		<edge to="(55|30)" weight="139.74970172765515" />
		<edge to="(16|23)" weight="256.03940464349716" />
		<edge to="(1|41)" weight="200.94076602694196" />
		<edge to="(52|60)" weight="167.46237686577055" />
		<edge to="(68|14)" weight="189.88119492620802" />
		<edge to="(43|88)" weight="445.7390904558883" />
		<edge to="(95|44)" weight="280.5848332146187" />
		<edge to="(5|52)" weight="364.127516304746" />
		<edge to="(60|75)" weight="214.71971726251633" />
		<edge to="(3|82)" weight="294.4875933051818" />
		<edge to="(29|47)" weight="230.01475134520592" />
		<edge to="(17|69)" weight="21.330769121091063" />
		<edge to="(5|58)" weight="0.0" />
		<edge to="(26|80)" weight="499.8604408613485" />
		<edge to="(58|18)" weight="128.74937021486153" />
		<edge to="(23|80)" weight="279.17296126793144" />
		<edge to="(25|53)" weight="217.16017786770658" />
		<edge to="(97|62)" weight="527.0996574722711" />
		<edge to="(57|22)" weight="99.35843949636656" />
		<edge to="(8|37)" weight="118.36386158574777" />
		<edge to="(16|46)" weight="60.95576629067596" />
	</node>
	<node label="(87|88)">
		<edge to="(87|88)" weight="0.0" />
		<edge to="(38|72)" weight="272.0281308439415" />
		<edge to="(5|71)" weight="90.07673719539258" />
		<edge to="(15|53)" weight="148.84794141275472" />
		<edge to="(55|30)" weight="476.01031389476844" />
		<edge to="(68|14)" weight="130.57282208203472" />
		<edge to="(41|20)" weight="399.18602895710006" />
		<edge to="(43|88)" weight="153.7232658530756" />
		<edge to="(60|75)" weight="257.6929755552196" />
		<edge to="(89|43)" weight="94.52530271750437" />
		<edge to="(60|48)" weight="452.169167595343" />
		<edge to="(26|80)" weight="503.39958050547585" />
		<edge to="(23|80)" weight="262.9060765147648" />
		<edge to="(2|62)" weight="575.3290936887754" />
		<edge to="(25|53)" weight="198.97967808131222" />
		<edge to="(57|22)" weight="541.4235396505409" />
		<edge to="(8|37)" weight="575.9904624136012" />
		<edge to="(38|35)" weight="115.36481961426949" />
		<edge to="(16|46)" weight="137.72299175336275" />
	</node>
	<node label="(38|72)">
		<edge to="(91|61)" weight="387.5035602943206" />
		<edge to="(38|72)" weight="0.0" />
		<edge to="(5|71)" weight="78.06403097990722" />
		<edge to="(16|23)" weight="126.21519727965689" />
		<edge to="(1|41)" weight="507.20162076560524" />
		<edge to="(8|17)" weight="218.5152551529952" />
		<edge to="(68|14)" weight="65.35180947694062" />
		<edge to="(5|52)" weight="205.9887745306769" />
		<edge to="(60|75)" weight="103.32840366900412" />
		<edge to="(3|82)" weight="71.97266038667632" />
		<edge to="(37|87)" weight="403.949527234921" />
		<edge to="(29|47)" weight="295.23315615090894" />
		<edge to="(17|69)" weight="199.2246047023012" />
		<edge to="(73|62)" weight="483.961486736194" />
		<edge to="(84|75)" weight="485.9047948525304" />
		<edge to="(24|47)" weight="200.29864254355346" />
		<edge to="(23|80)" weight="381.62929117745625" />
		<edge to="(98|91)" weight="555.7340864924114" />
		<edge to="(74|36)" weight="469.87594632292627" />
		<edge to="(19|77)" weight="346.46983181992516" />
		<edge to="(92|23)" weight="211.07320247682588" />
		<edge to="(2|62)" weight="449.91916665166724" />
		<edge to="(16|46)" weight="329.36373554771444" />
	</node>
	<node label="(5|71)">
		<edge to="(77|77)" weight="281.8608225409689" />
		<edge to="(91|61)" weight="221.27399745447664" />
		<edge to="(5|71)" weight="0.0" />
		<edge to="(43|47)" weight="461.1217908221566" />
		<edge to="(15|53)" weight="219.88271407955452" />
		<edge to="(1|41)" weight="286.4395533639388" />
		<edge to="(7|16)" weight="249.49007004770414" />
		<edge to="(8|17)" weight="300.976909293616" />
		<edge to="(68|14)" weight="401.0129115950015" />
		<edge to="(41|20)" weight="262.44214547301794" />
		<edge to="(95|44)" weight="513.5359618795886" />
		<edge to="(3|82)" weight="195.3158528191082" />
		<edge to="(37|87)" weight="467.27219138015516" />
		<edge to="(89|43)" weight="410.76324310408415" />
		<edge to="(29|47)" weight="183.91209969505928" />
		<edge to="(12|62)" weight="334.38818114920866" />
		<edge to="(60|48)" weight="331.81491505100416" />
		<edge to="(84|75)" weight="303.59501091718676" />
		<edge to="(58|18)" weight="521.4309925049366" />
		<edge to="(92|23)" weight="175.0444284668206" />
		<edge to="(2|62)" weight="70.85541853546563" />
		<edge to="(97|62)" weight="311.4630810790683" />
		<edge to="(57|22)" weight="547.6222988960496" />
		<edge to="(38|35)" weight="456.54168790680006" />
	</node>
	<node label="(43|47)">
		<edge to="(87|88)" weight="548.2626247512811" />
		<edge to="(91|61)" weight="52.10495088315221" />
		<edge to="(5|71)" weight="396.1097778768808" />
		<edge to="(19|54)" weight="283.02275387170795" />
		<edge to="(43|47)" weight="0.0" />
		<edge to="(67|73)" weight="61.07248267722346" />
		<edge to="(7|16)" weight="170.53398954859108" />
		<edge to="(8|17)" weight="206.58010243011174" />
		<edge to="(68|14)" weight="240.7699140325924" />
		<edge to="(41|20)" weight="371.07843335124255" />
		<edge to="(5|52)" weight="446.26418984293565" />
		<edge to="(60|75)" weight="159.41513712794253" />
		<edge to="(89|43)" weight="219.71468194540654" />
		<edge to="(12|62)" weight="159.46130069763134" />
		<edge to="(26|80)" weight="373.3753896649396" />
		<edge to="(24|47)" weight="184.17491255688415" />
		<edge to="(23|80)" weight="523.5237215319912" />
		<edge to="(98|91)" weight="213.06041198819952" />
		<edge to="(74|36)" weight="217.9848612954954" />
		<edge to="(25|53)" weight="141.6518438798155" />
		<edge to="(97|62)" weight="413.1547324442888" />
		<edge to="(8|37)" weight="148.0785787091969" />
	</node>
	<node label="(67|73)">
		<edge to="(51|18)" weight="270.13639636671246" />
		<edge to="(91|61)" weight="264.973957389581" />
		<edge to="(55|30)" weight="255.72417427679122" />
		<edge to="(16|23)" weight="206.03988849737453" />
		<edge to="(1|41)" weight="217.95071528230244" />
		<edge to="(52|60)" weight="356.7945556372726" />
		<edge to="(68|14)" weight="518.6568506490187" />
		<edge to="(5|52)" weight="530.6240186085645" />
		<edge to="(60|75)" weight="21.852780693348173" />
		<edge to="(35|20)" weight="320.4644472401377" />
		<edge to="(5|58)" weight="447.6045754737634" />
		<edge to="(58|18)" weight="438.80579889603433" />
		<edge to="(19|77)" weight="462.37699194022974" />
		<edge to="(57|51)" weight="61.96712960113158" />
		<edge to="(8|37)" weight="166.1754740660157" />
		<edge to="(16|46)" weight="503.11521422514943" />
		<edge to="(77|77)" weight="410.4678940817384" />
		<edge to="(5|71)" weight="170.7430399635054" />
		<edge to="(43|47)" weight="455.6485818366557" />
		<edge to="(67|73)" weight="0.0" />
		<edge to="(7|16)" weight="296.17005290100496" />
		<edge to="(95|44)" weight="208.47398727494763" />
		<edge to="(3|82)" weight="336.0077663843466" />
		<edge to="(89|43)" weight="233.42112777213993" />
		<edge to="(84|75)" weight="139.51023626757618" />
		<edge to="(98|91)" weight="97.09212598781082" />
		<edge to="(92|23)" weight="180.36554433873874" />
		<edge to="(2|62)" weight="149.3971875065397" />
		<edge to="(25|53)" weight="54.74062626724651" />
		<edge to="(97|62)" weight="284.91144293691303" />
		<edge to="(38|35)" weight="131.6129477078561" />
	</node>
	<node label="(7|16)">
		<edge to="(51|18)" weight="274.0445959277077" />
		<edge to="(87|88)" weight="331.8114530453097" />
		<edge to="(38|72)" weight="524.8386176431525" />
		<edge to="(55|30)" weight="76.8743592238514" />
		<edge to="(7|16)" weight="0.0" />
		<edge to="(8|17)" weight="287.4161543764629" />
		<edge to="(68|14)" weight="441.66183836862723" />
		<edge to="(41|20)" weight="321.9876477743223" />
		<edge to="(43|88)" weight="123.99090709441779" />
		<edge to="(3|82)" weight="462.73810467863774" />
		<edge to="(37|87)" weight="227.5278883405276" />
		<edge to="(17|69)" weight="283.1237641026324" />
		<edge to="(73|62)" weight="551.5252608920783" />
		<edge to="(26|80)" weight="79.68062670040835" />
		<edge to="(24|47)" weight="145.76583051687112" />
		<edge to="(58|18)" weight="451.89040654688694" />
		<edge to="(23|80)" weight="348.0987951704655" />
		<edge to="(98|91)" weight="445.98599610287636" />
		<edge to="(57|51)" weight="124.8835821507771" />
		<edge to="(2|62)" weight="84.07246089932124" />
		<edge to="(25|53)" weight="516.5229864820037" />
		<edge to="(97|62)" weight="452.39333303953106" />
		<edge to="(16|46)" weight="438.9166354855106" />
	</node>
	<node label="(89|43)">
		<edge to="(77|77)" weight="447.1440751000432" />
		<edge to="(87|88)" weight="219.7761050389117" />
		<edge to="(38|72)" weight="476.8943281763395" />
		<edge to="(15|53)" weight="215.09426852295968" />
		<edge to="(55|30)" weight="468.98212214518355" />
		<edge to="(7|16)" weight="480.3779471036869" />
		<edge to="(68|14)" weight="507.77847381816264" />
		<edge to="(60|75)" weight="354.145526780351" />
		<edge to="(3|82)" weight="113.97585383053075" />
		<edge to="(89|43)" weight="0.0" />
		<edge to="(60|48)" weight="244.96441724209834" />
		<edge to="(73|62)" weight="197.6780108734677" />
		<edge to="(26|80)" weight="363.0348633441272" />
		<edge to="(24|47)" weight="399.7327344771455" />
		<edge to="(23|80)" weight="274.3797046430699" />
		<edge to="(57|51)" weight="195.11372155354204" />
		<edge to="(97|62)" weight="152.56681222189664" />
		<edge to="(16|46)" weight="230.30763822990565" />
	</node>
	<node label="(60|48)">
		<edge to="(51|18)" weight="115.16961042953298" />
		<edge to="(91|61)" weight="330.226965278519" />
		<edge to="(19|54)" weight="180.09439732588626" />
		<edge to="(15|53)" weight="213.63712591991222" />
		<edge to="(55|30)" weight="320.0055479497448" />
		<edge to="(1|41)" weight="112.37692805271472" />
		<edge to="(52|60)" weight="158.8985946887517" />
		<edge to="(41|20)" weight="527.2757935461036" />
		<edge to="(5|52)" weight="293.2614239783597" />
		<edge to="(37|87)" weight="70.37393086500154" />
		<edge to="(17|69)" weight="175.9343082664503" />
		<edge to="(5|58)" weight="483.79312128333373" />
		<edge to="(73|62)" weight="301.37358039013515" />
		<edge to="(24|47)" weight="374.83522184036264" />
		<edge to="(23|80)" weight="403.5645629709091" />
		<edge to="(74|36)" weight="396.0032144562524" />
		<edge to="(77|77)" weight="485.4113637547672" />
		<edge to="(45|45)" weight="334.3729101514308" />
		<edge to="(38|72)" weight="282.0074183321954" />
		<edge to="(5|71)" weight="475.32527060473456" />
		<edge to="(43|47)" weight="348.4215132919339" />
		<edge to="(3|82)" weight="262.2453138859554" />
		<edge to="(89|43)" weight="371.67248187892653" />
		<edge to="(12|62)" weight="125.00021433207942" />
		<edge to="(60|48)" weight="0.0" />
		<edge to="(84|75)" weight="218.09259933518092" />
		<edge to="(25|53)" weight="502.372221540062" />
		<edge to="(97|62)" weight="231.72593459975508" />
	</node>
	<node label="(26|80)">
		<edge to="(91|61)" weight="204.75393990015164" />
		<edge to="(19|54)" weight="383.1689758009417" />
		<edge to="(15|53)" weight="483.1772776845718" />
		<edge to="(8|17)" weight="166.20852680018834" />
		<edge to="(43|88)" weight="110.03633757230689" />
		<edge to="(5|52)" weight="45.27050999106416" />
		<edge to="(60|75)" weight="46.342329355000665" />
		<edge to="(35|20)" weight="477.05700873036255" />
		<edge to="(17|69)" weight="165.4417673292623" />
		<edge to="(73|62)" weight="498.05238594817934" />
		<edge to="(23|80)" weight="195.8517534133418" />
		<edge to="(77|77)" weight="124.01834363416393" />
		<edge to="(87|88)" weight="370.2055478452322" />
		<edge to="(38|72)" weight="364.12593997841" />
		<edge to="(5|71)" weight="356.37229491267107" />
		<edge to="(7|16)" weight="102.26374254380292" />
		<edge to="(95|44)" weight="161.61281435666825" />
		<edge to="(29|47)" weight="276.455319706654" />
		<edge to="(12|62)" weight="73.47937876969557" />
		<edge to="(26|80)" weight="0.0" />
		<edge to="(98|91)" weight="275.19684852910484" />
		<edge to="(92|23)" weight="199.0571367445694" />
		<edge to="(2|62)" weight="526.9530692265763" />
		<edge to="(25|53)" weight="211.05073328759673" />
		<edge to="(97|62)" weight="177.67718297811643" />
		<edge to="(57|22)" weight="410.411609254582" />
		<edge to="(38|35)" weight="449.392250713664" />
	</node>
	<node label="(84|75)">
		<edge to="(51|18)" weight="348.68321680715485" />
		<edge to="(91|61)" weight="428.01938770657" />
		<edge to="(19|54)" weight="275.93859198903414" />
		<edge to="(16|23)" weight="246.77380403180524" />
		<edge to="(68|14)" weight="510.3782751571761" />
		<edge to="(41|20)" weight="542.8740220464027" />
		<edge to="(60|75)" weight="476.42476368740813" />
		<edge to="(24|47)" weight="480.85893982783443" />
		<edge to="(74|36)" weight="361.9420452926746" />
		<edge to="(19|77)" weight="512.1953183320566" />
		<edge to="(16|46)" weight="432.8576184989338" />
		<edge to="(45|45)" weight="80.47524883014252" />
		<edge to="(87|88)" weight="408.17800166191483" />
		<edge to="(38|72)" weight="85.25294251336327" />
		<edge to="(5|71)" weight="185.51488490728372" />
		<edge to="(7|16)" weight="183.56388552838666" />
		<edge to="(95|44)" weight="342.41252293883934" />
		<edge to="(3|82)" weight="112.5219634031664" />
		<edge to="(89|43)" weight="120.66651890266246" />
		<edge to="(29|47)" weight="392.5113412485373" />
		<edge to="(12|62)" weight="205.81968326869733" />
		<edge to="(26|80)" weight="318.57390253931595" />
		<edge to="(84|75)" weight="0.0" />
		<edge to="(98|91)" weight="70.22404829287368" />
		<edge to="(2|62)" weight="385.28603198839164" />
		<edge to="(97|62)" weight="329.8002730571458" />
	</node>
	<node label="(2|62)">
		<edge to="(51|18)" weight="98.50319146548156" />
		<edge to="(45|45)" weight="377.6041003187957" />
		<edge to="(1|41)" weight="131.29538632727295" />
		<edge to="(5|52)" weight="96.8461742227217" />
		<edge to="(37|87)" weight="62.6343710122804" />
		<edge to="(89|43)" weight="354.5414983085492" />
		<edge to="(29|47)" weight="65.88817948173227" />
		<edge to="(17|69)" weight="38.54985211827979" />
		<edge to="(60|48)" weight="287.1634632223704" />
		<edge to="(5|58)" weight="230.6648786631325" />
		<edge to="(73|62)" weight="248.91906058336926" />
		<edge to="(24|47)" weight="358.9210754232781" />
		<edge to="(58|18)" weight="178.19981275490022" />
		<edge to="(23|80)" weight="278.7006119220149" />
		<edge to="(19|77)" weight="281.9420920024215" />
		<edge to="(2|62)" weight="0.0" />
		<edge to="(25|53)" weight="30.736906161012328" />
		<edge to="(57|22)" weight="439.58460866302437" />
		<edge to="(38|35)" weight="237.07269547027656" />
	</node>
	<node label="(97|62)">
		<edge to="(91|61)" weight="42.576651849082" />
		<edge to="(15|53)" weight="116.07617731876742" />
		<edge to="(1|41)" weight="385.782951273867" />
		<edge to="(52|60)" weight="287.71730660253405" />
		<edge to="(8|17)" weight="177.90567818058102" />
		<edge to="(41|20)" weight="309.9840293946139" />
		<edge to="(60|75)" weight="121.3027271937227" />
		<edge to="(37|87)" weight="256.9196145336315" />
		<edge to="(17|69)" weight="275.5384168995653" />
		<edge to="(5|58)" weight="402.67123120834765" />
		<edge to="(73|62)" weight="425.814515219093" />
		<edge to="(24|47)" weight="418.4474719056167" />
		<edge to="(58|18)" weight="127.75300464037673" />
		<edge to="(74|36)" weight="250.80702043243213" />
		<edge to="(19|77)" weight="455.24332871926686" />
		<edge to="(57|51)" weight="156.06047250084598" />
		<edge to="(45|45)" weight="500.38464367996744" />
		<edge to="(38|72)" weight="137.53365402588943" />
		<edge to="(5|71)" weight="259.31784842960735" />
		<edge to="(43|47)" weight="544.15159954405" />
		<edge to="(7|16)" weight="221.33489024725532" />
		<edge to="(29|47)" weight="434.8281066197666" />
		<edge to="(26|80)" weight="470.6119480206717" />
		<edge to="(84|75)" weight="490.0998678731083" />
		<edge to="(92|23)" weight="308.2780495464384" />
		<edge to="(97|62)" weight="0.0" />
		<edge to="(57|22)" weight="79.2629942944553" />
		<edge to="(38|35)" weight="150.58726184453127" />
	</node>
	<node label="(57|22)">
		<edge to="(91|61)" weight="441.390253196381" />
		<edge to="(19|54)" weight="482.2869802682309" />
		<edge to="(55|30)" weight="462.7620611852883" />
		<edge to="(16|23)" weight="513.8011937527581" />
		<edge to="(52|60)" weight="151.745674284777" />
		<edge to="(8|17)" weight="65.21045344443209" />
		<edge to="(5|52)" weight="419.410805753461" />
		<edge to="(60|75)" weight="356.07025473830197" />
		<edge to="(35|20)" weight="200.23602198872067" />
		<edge to="(5|58)" weight="329.68617687428446" />
		<edge to="(73|62)" weight="169.94676342780357" />
		<edge to="(58|18)" weight="400.82180717562125" />
		<edge to="(74|36)" weight="195.69697509596233" />
		<edge to="(57|51)" weight="300.3777958863159" />
		<edge to="(16|46)" weight="451.8693724917254" />
		<edge to="(77|77)" weight="341.89860400153356" />
		<edge to="(45|45)" weight="333.22439226674027" />
		<edge to="(38|72)" weight="355.8019695690059" />
		<edge to="(5|71)" weight="453.64129395550583" />
		<edge to="(43|47)" weight="80.41107308368206" />
		<edge to="(67|73)" weight="482.5657717072865" />
		<edge to="(7|16)" weight="300.765284690621" />
		<edge to="(95|44)" weight="278.01270655374367" />
		<edge to="(3|82)" weight="171.2635909631441" />
		<edge to="(89|43)" weight="467.83668826415396" />
		<edge to="(12|62)" weight="352.2080171372853" />
		<edge to="(26|80)" weight="504.90161756822164" />
		<edge to="(84|75)" weight="347.31111754436927" />
		<edge to="(2|62)" weight="345.22363566179325" />
		<edge to="(97|62)" weight="241.69483312948984" />
		<edge to="(57|22)" weight="0.0" />
	</node>
	<node label="(19|54)">
		<edge to="(51|18)" weight="355.4730627180071" />
		<edge to="(91|61)" weight="354.8595635707751" />
		<edge to="(19|54)" weight="0.0" />
		<edge to="(16|23)" weight="392.7494988993558" />
		<edge to="(1|41)" weight="465.0839348511351" />