<?xml version="1.0"?>
<!DOCTYPE graph [
	<!ELEMENT graph (node)*>
	<!ELEMENT node (edge)*>
	<!ELEMENT edge EMPTY>

	<!ATTLIST node
		label CDATA #REQUIRED
	>
	<!ATTLIST edge
		to     CDATA #REQUIRED
		weight CDATA #REQUIRED
	>
]>


<graph>
	<node label="(77|77)">
		<edge to="(3|82)" weight="138.617302000043" />
		<edge to="(77|77)" weight="0.0" />
		<edge to="(91|61)" weight="339.9690043005234" />
		<edge to="(29|47)" weight="68.22294803428434" />
		<edge to="(73|62)" weight="328.0973564290397" />
		<edge to="(84|75)" weight="395.4362555267468" />
		<edge to="(52|60)" weight="222.8270252860212" />
		<edge to="(92|23)" weight="429.1653277379735" />
	</node>
	<node label="(45|45)">
		<edge to="(3|82)" weight="225.35803464450294" />
		<edge to="(45|45)" weight="0.0" />
		<edge to="(19|54)" weight="69.04483209685266" />
		<edge to="(84|75)" weight="157.98886450541318" />
		<edge to="(92|23)" weight="398.0406264577831" />
		<edge to="(95|44)" weight="281.4889082114114" />
		<edge to="(43|88)" weight="78.79564394000883" />
		<edge to="(38|35)" weight="403.75280049932337" />
	</node>
	<node label="(91|61)">
		<edge to="(45|45)" weight="245.80495903620923" />
		<edge to="(91|61)" weight="0.0" />
		<edge to="(37|87)" weight="290.97729139808405" />
		<edge to="(92|23)" weight="61.64609021556113" />
		<edge to="(2|62)" weight="103.55937416104442" />
		<edge to="(25|53)" weight="552.4581410312512" />
		<edge to="(95|44)" weight="498.4987083003423" />
	</node>
	<node label="(19|54)">
		<edge to="(91|61)" weight="226.91857108972113" />
		<edge to="(37|87)" weight="474.72099740002216" />
		<edge to="(19|54)" weight="0.0" />
		<edge to="(84|75)" weight="391.670075951197" />
		<edge to="(24|47)" weight="261.95312324346895" />
		<edge to="(52|60)" weight="38.62874693061147" />
		<edge to="(41|20)" weight="83.86584104549694" />
		<edge to="(2|62)" weight="257.6067501065166" />
		<edge to="(43|88)" weight="195.56388791060598" />
		<edge to="(38|35)" weight="32.6974768233627" />
	</node>
	<node label="(15|53)">
		<edge to="(29|47)" weight="191.75779593333766" />
		<edge to="(19|54)" weight="198.64469740243192" />
		<edge to="(15|53)" weight="0.0" />
		<edge to="(41|20)" weight="43.96866838381045" />
		<edge to="(92|23)" weight="352.75246585022626" />
		<edge to="(95|44)" weight="526.9131368284075" />
		<edge to="(43|88)" weight="259.2741093268987" />
		<edge to="(38|35)" weight="373.7149210036914" />
	</node>
	<node label="(52|60)">
		<edge to="(3|82)" weight="318.4785838142272" />
		<edge to="(29|47)" weight="83.36070194607746" />
		<edge to="(60|48)" weight="310.6367264139853" />
		<edge to="(15|53)" weight="412.83215973999927" />
		<edge to="(24|47)" weight="197.73553667315844" />
		<edge to="(52|60)" weight="0.0" />
		<edge to="(41|20)" weight="102.73560077775883" />
		<edge to="(92|23)" weight="422.2587133938655" />
		<edge to="(2|62)" weight="182.3136762559492" />
		<edge to="(25|53)" weight="176.7733422719886" />
	</node>
	<node label="(41|20)">
		<edge to="(77|77)" weight="110.45089911188447" />
		<edge to="(29|47)" weight="286.13999720787353" />
		<edge to="(19|54)" weight="306.17318630999665" />
		<edge to="(60|48)" weight="488.74871837302373" />
		<edge to="(73|62)" weight="189.90620259618984" />
		<edge to="(15|53)" weight="130.3964268091952" />
		<edge to="(24|47)" weight="63.90230548232164" />
		<edge to="(41|20)" weight="0.0" />
		<edge to="(92|23)" weight="121.12165608507075" />
		<edge to="(95|44)" weight="552.0460599242841" />
		<edge to="(38|35)" weight="327.9785779412389" />
	</node>
	<node label="(95|44)">
		<edge to="(77|77)" weight="276.271709683073" />
		<edge to="(45|45)" weight="405.3232324195318" />
		<edge to="(91|61)" weight="427.1380039494959" />
		<edge to="(60|48)" weight="132.80670740117898" />
		<edge to="(24|47)" weight="140.1598010998909" />
		<edge to="(52|60)" weight="218.16067052220092" />
		<edge to="(41|20)" weight="431.66673074987716" />
		<edge to="(92|23)" weight="431.0599842233827" />
		<edge to="(25|53)" weight="310.5492938109064" />
		<edge to="(95|44)" weight="0.0" />
		<edge to="(43|88)" weight="142.88306157823865" />
	</node>
	<node label="(43|88)">
		<edge to="(37|87)" weight="37.960740578860516" />
		<edge to="(19|54)" weight="42.437617458240496" />
		<edge to="(60|48)" weight="303.91079139473743" />
		<edge to="(24|47)" weight="297.8666649217561" />
		<edge to="(41|20)" weight="319.71032945552975" />
		<edge to="(2|62)" weight="223.2311413107775" />
		<edge to="(43|88)" weight="0.0" />
		<edge to="(38|35)" weight="183.25274194893854" />
	</node>
	<node label="(3|82)">
		<edge to="(77|77)" weight="277.3748426830135" />
		<edge to="(45|45)" weight="202.72743163606947" />
		<edge to="(19|54)" weight="218.11851540767296" />
		<edge to="(15|53)" weight="300.5985320840565" />
		<edge to="(52|60)" weight="208.74472104303754" />
		<edge to="(43|88)" weight="508.26310801423415" />
		<edge to="(3|82)" weight="0.0" />
		<edge to="(60|48)" weight="255.5138598596152" />
		<edge to="(84|75)" weight="98.6050808497312" />
		<edge to="(92|23)" weight="467.63226842471397" />
		<edge to="(2|62)" weight="165.42672408503566" />
		<edge to="(25|53)" weight="99.0187819788429" />
		<edge to="(38|35)" weight="227.39454550079347" />
	</node>
	<node label="(29|47)">
		<edge to="(91|61)" weight="373.679626603772" />
		<edge to="(29|47)" weight="0.0" />
		<edge to="(37|87)" weight="532.3745498744886" />
		<edge to="(19|54)" weight="219.8724792936953" />
		<edge to="(84|75)" weight="139.9052269776165" />
		<edge to="(24|47)" weight="131.08502727370154" />
		<edge to="(41|20)" weight="160.21799005332537" />
		<edge to="(92|23)" weight="201.75684013006497" />
		<edge to="(2|62)" weight="90.15832771209226" />
		<edge to="(43|88)" weight="413.9151432044022" />
	</node>
	<node label="(37|87)">
		<edge to="(77|77)" weight="501.8843401895672" />
		<edge to="(45|45)" weight="528.9203721870606" />
		<edge to="(91|61)" weight="317.63594844304737" />
		<edge to="(29|47)" weight="113.49678885942339" />
		<edge to="(37|87)" weight="0.0" />
		<edge to="(19|54)" weight="110.20470893177375" />
		<edge to="(60|48)" weight="233.30288279081716" />
		<edge to="(52|60)" weight="140.19473233491772" />
		<edge to="(41|20)" weight="472.66141372462306" />
		<edge to="(2|62)" weight="251.62328918977926" />
		<edge to="(95|44)" weight="341.19485995975424" />
		<edge to="(38|35)" weight="134.44513760944386" />
	</node>
	<node label="(60|48)">
		<edge to="(91|61)" weight="220.61855715226648" />
		<edge to="(29|47)" weight="292.4409505435622" />
		<edge to="(37|87)" weight="379.7573446942473" />
		<edge to="(19|54)" weight="103.85091500669812" />
		<edge to="(60|48)" weight="0.0" />
		<edge to="(84|75)" weight="233.20736499161768" />
		<edge to="(41|20)" weight="197.94750943931302" />
		<edge to="(92|23)" weight="108.75929319537505" />
		<edge to="(2|62)" weight="355.7093563605496" />
		<edge to="(25|53)" weight="475.1282146848208" />
		<edge to="(43|88)" weight="63.950107300167886" />
		<edge to="(38|35)" weight="291.141773744472" />
	</node>
	<node label="(73|62)">
		<edge to="(37|87)" weight="120.5690354563298" />
		<edge to="(19|54)" weight="83.65428574518475" />
		<edge to="(60|48)" weight="488.98194541837734" />
		<edge to="(73|62)" weight="0.0" />
		<edge to="(15|53)" weight="264.9331997004174" />
		<edge to="(24|47)" weight="529.0832901326401" />
		<edge to="(92|23)" weight="148.4188091564585" />
		<edge to="(38|35)" weight="118.64147278607018" />
	</node>
	<node label="(84|75)">
		<edge to="(37|87)" weight="350.47107455927807" />
		<edge to="(19|54)" weight="269.71205162913515" />
		<edge to="(60|48)" weight="463.780974493964" />
		<edge to="(84|75)" weight="0.0" />
		<edge to="(24|47)" weight="287.62419292153845" />
		<edge to="(52|60)" weight="495.8435586385865" />
		<edge to="(41|20)" weight="485.1950144395679" />
		<edge to="(25|53)" weight="426.88730339892743" />
		<edge to="(95|44)" weight="417.7026346377049" />
		<edge to="(38|35)" weight="272.56657644872246" />
	</node>
	<node label="(24|47)">
		<edge to="(77|77)" weight="432.589658015719" />
		<edge to="(91|61)" weight="446.52337384102174" />
		<edge to="(19|54)" weight="495.06713401778467" />
		<edge to="(15|53)" weight="121.14496095543699" />
		<edge to="(43|88)" weight="347.80885073808344" />
		<edge to="(29|47)" weight="147.17589813235466" />
		<edge to="(60|48)" weight="131.59852031576054" />
		<edge to="(84|75)" weight="105.76276656742914" />
		<edge to="(24|47)" weight="0.0" />
		<edge to="(92|23)" weight="172.4120915359307" />
		<edge to="(2|62)" weight="72.01618227438306" />
		<edge to="(25|53)" weight="367.29805620434877" />
		<edge to="(38|35)" weight="503.633569168816" />
	</node>
	<node label="(92|23)">
		<edge to="(3|82)" weight="263.16747333819916" />
		<edge to="(37|87)" weight="240.40812882233382" />
		<edge to="(19|54)" weight="296.86509477894424" />
		<edge to="(15|53)" weight="456.49755615371953" />
		<edge to="(24|47)" weight="176.4376476245833" />
		<edge to="(52|60)" weight="402.85010122025363" />
		<edge to="(41|20)" weight="72.85688821199093" />
		<edge to="(92|23)" weight="0.0" />
		<edge to="(43|88)" weight="510.9368956303541" />
		<edge to="(38|35)" weight="481.08370169143143" />
	</node>
	<node label="(2|62)">
		<edge to="(77|77)" weight="366.3370993948769" />
		<edge to="(45|45)" weight="341.4502857191192" />
		<edge to="(19|54)" weight="271.914571735532" />
		<edge to="(41|20)" weight="461.76658402323704" />
		<edge to="(95|44)" weight="305.76629395848676" />
		<edge to="(43|88)" weight="191.17929050541343" />
		<edge to="(29|47)" weight="339.12083743649356" />
		<edge to="(37|87)" weight="330.2253694544704" />
		<edge to="(60|48)" weight="298.62795543166106" />
		<edge to="(73|62)" weight="378.3541261792097" />
		<edge to="(84|75)" weight="98.37589701988357" />
		<edge to="(92|23)" weight="497.8342810492751" />
		<edge to="(2|62)" weight="0.0" />
	</node>
	<node label="(25|53)">
		<edge to="(3|82)" weight="50.67105473151402" />
		<edge to="(77|77)" weight="529.2003887249103" />
		<edge to="(29|47)" weight="208.10808163949463" />
		<edge to="(60|48)" weight="508.4635904017275" />
		<edge to="(84|75)" weight="244.72348875302555" />
		<edge to="(24|47)" weight="46.48593495337539" />
		<edge to="(25|53)" weight="0.0" />
		<edge to="(95|44)" weight="200.5170474990204" />
	</node>
	<node label="(38|35)">
		<edge to="(91|61)" weight="474.8395300152905" />
		<edge to="(19|54)" weight="305.0899022900672" />
		<edge to="(15|53)" weight="242.01952595912473" />
		<edge to="(52|60)" weight="69.50636761521028" />
		<edge to="(41|20)" weight="226.9043470882996" />
		<edge to="(95|44)" weight="140.32089120504065" />
		<edge to="(3|82)" weight="178.70100825876685" />
		<edge to="(37|87)" weight="537.2477199332533" />
		<edge to="(60|48)" weight="292.0613665106041" />
		<edge to="(84|75)" weight="125.31205586811296" />
		<edge to="(92|23)" weight="256.2994180001506" />
		<edge to="(2|62)" weight="310.1355533473276" />
		<edge to="(25|53)" weight="394.6989819439473" />
		<edge to="(38|35)" weight="0.0" />
	</node>
</graph>